### ISSUE TITLE
How to glob template folder recursively?

### ISSUE THREAD

**Issue by BassOfBass** [JDeuce/python-jinja2-webpack#4]
Let's say with structure like this:
```
|src
  |assets
    |folder
      ...files
    assets.js
    ...files
  |templates
    |partials
      ...files
    ...files
```
Only files either from `partials` or `templates` can be scanned at a time, and that results in a different non-cumulative `assets.js`.

There is also a quirk in how scanner filters `{{ 'name' | webpack }}` versus how the package filters them on server. Scanner runs relative paths while the server maps the paths according to manifest. From the example above scanner requires `{{ folder/file | webpack }}` scheme to pick up the target for import, but once imported the final path depends only on the config module ruleset, not the source path.

**Comment by JDeuce** [comment]
You should definitely scan your stuff together to a single assets.js.

I think you can probably run something like `templates/**.jinja2` for that but you can always just pass multiple globs to the scanner, there's no requirement that you have to make a single glob.

For the scanner filters you should be able to tune the base root path with --root and --reference-root in order to get your relative paths working correct.

Feel free to send a pull request if you fix anything, tbh I haven't been running this for a few years now and I only used it in a few simple apps back in the day. Cheers, good luck.

**Comment by BassOfBass** [comment]
> I think you can probably run something like `templates/**.jinja2` for that but you can always just pass multiple globs to the scanner, there's no requirement that you have to make a single glob.

How do you pass multiple globs as a CLI argument though? A single string with comma-separated arguments? Several comma-separated strings? An array-like construct of strings?

> For the scanner filters you should be able to tune the base root path with --root and --reference-root in order to get your relative paths working correct.

Well, there is a lot of path options and the doc example is pretty sparse on details, that's why I got lost.

> Feel free to send a pull request if you fix anything, tbh I haven't been running this for a few years now and I only used it in a few simple apps back in the day. Cheers, good luck.

Sadly I don't know Python. I was only searching for a way to move frontend of a flask project to the webpack pipeline with minimal friction and this package does its job so far. By "not running this for few years" do you mean you didn't have flask + webpack projects for a while or is there a better way to go about it? Because any info related to flask+webpack is pretty scarce, let alone with jinja on top, and I haven't even gotten to webpack dev server setup yet.

**Comment by JDeuce** [comment]
For the scanner you just give it multiple globs for the CLI...

jinja2-webpack-scan \
    -o webpack-asset-entries.js \
    -d 'templates/' \
    --root 'project/' \
    'templates/*.jinja2' \
    'templates/partials/*.jinja2'
    
 That command has a --help option you can look at as well.
 
 Yeah I've just been focused on other areas of tech (not making python webapps). If you want to use webpack on the server I think this still makes a lot of sense, but most people in the web world are fully isolating their frontend dependencies to separate projects now too. 
 
 I always used it with pyramid but yeah should work well with flask too. You can check this if you haven't seen it, might be another good reference anyway. https://github.com/JDeuce/python-pyramid-jinja2-webpack Feel free to contribute any changes to docs or anything you think can help someone else
